language: objective-c
osx_image: xcode9.2
branches:
  only:
    - master
before_install:
  - brew install carthage
script:
  - carthage build --no-skip-current
  - xcodebuild -scheme "CommonUtilityTests" -destination "platform=iOS Simulator,name=iPhone 5s" test
